### ISSUE TITLE
No Colors on Pebble Time

### ISSUE THREAD

**Issue by phillipthelen** [kdemerath/Habitica-Tasks#10]
The app could use some awesome color on the pebble time! Pebbles Indigo color looks pretty close to Habiticas purple and could be used for the menu selection highlight.

**Comment by kdemerath** [comment]
is the icon at the start card colored?

**Comment by kdemerath** [comment]
implemented `.highlightBackgroundColor = 'indigo'` for the basalt platform based watches.
