### ISSUE TITLE
Task scoring card only appears if task has up and down action

### ISSUE THREAD

**Issue by phillipthelen** [kdemerath/Habitica-Tasks#7]
At least if I read the code correct it requires both an up and a down action to open the scoring card.

**Comment by kdemerath** [comment]
Thats right. If it is a daily or a todo the scoring card is not neccessary. you just mark it complete. if it is a habit and the habit has only one direction this habit is scored in this direction. only if a habit has two directions the user has to choose one. imho this is the most lean way to do it.
for better understanding: if you select a task and press "select" there is no response. it is immediately marked as completed.

**Comment by phillipthelen** [comment]
Imho this isn't good usability. Before doing selecting a habit p.e. the user has no way of knowing what will happen. I scored habits several times because I expected a card to appear where I select if I want to score the task up or down. Imho the card should always be displayed (and only have the appropriate actions depending on the specific task) to make it clearer what is happening and to have a more consistent user experience.

**Comment by kdemerath** [comment]
I described it in the app description. And now it is more precisely. What do you @vIiRuS think about a response screen 'You scored your Habit down/up' / 'Your marked your Daily/To-Do completed' showing a second or so?

**Comment by phillipthelen** [comment]
Feedback that the action was successful ist also important. But doesn't solve the problem that a user doesn't know beforehand what will happen. If they score a habit with up and down action it will display the detail card with action selection. But when they then want to score a task with only up or down action it will score directly, instead of displaying a detail screen with selection. That might be ok if they want to up/downscore the task anyway, but if they want to use an action that isn't available they don't get what they want.

**Comment by kdemerath** [comment]
I do not understand your concern. Or lets say somehow a litle bit. But, I asume a user knows his tasks. He sees if the task is a habit or not. The watchapp description is clear. There is nothing else a user can do with a task. He will max. have one use of the select button in error -> He sees the response screen and understands. Then there will be a refresh after a task marking complete in the future. See issue #12 This will make it also clear to the user what happened. The task he selected disappears. Everything is good. Another thing came just into my mind: Task icons like unchecked checkbox for dailies and todos and +, - or +/- or nothing for habits. But this would take some of the spare space.

**Comment by kdemerath** [comment]
Going to implement #14 and #12 to enhance user experience with task list and working with tasks.
