### ISSUE TITLE
Separate habits, dailies and todos

### ISSUE THREAD

**Issue by phillipthelen** [kdemerath/Habitica-Tasks#8]
I think it would be better to have habits, dailies and todos in separate lists. The selection could be moved up one level, so that the app starts with a view of the logo (if that should be kept) and then the selection of the three task types, which opens the matching lists.

**Comment by kdemerath** [comment]
would make this configurable in the settings. if the user likes to score its habits fast there is no separation, for them who need to access their todos faster separation could be switched on.

**Comment by phillipthelen** [comment]
The way it currently is handled the separation actually wouldn't add an additional button press for accessing habits, thus not making it any slower.
Currently:
first screen -> press down -> list of habits

Then: 
first screen with "Habits" preselected, as it's the first item -> select -> list of habits

Splitting has the advantage that loading/displaying the tasks is potentially faster if the user has a larger amount of tasks.

**Comment by kdemerath** [comment]
The welcome screen might be kept for e.g. pressing "up" the get user stats (hp/exp/mana).
Loading time is not affected becaus the habitica-api only let me load all tasks. As far as I know. I am not an experinced api user.

**Comment by phillipthelen** [comment]
The stats could be available in the same menu as the task types, resulting in
- Profile/Stats
- Habits
- Dailies
- To-Dos

Yes, the API only returns all tasks. but if that is done when the app is opened (and the top level menu/welcome screen is displayed) the time it takes to load the tasks in the menu would probably be reduced. (as it only takes p.e. habits from the list and creates a menu from them )

**Comment by excentris** [comment]
I agree with @vIiRuS. It would be nice to split the lists selection. I would put the Profile/Stats at the end, though, like:
- Habits
- Dailies
- To-Dos
- Profile/Stats

**Comment by kdemerath** [comment]
Yeah! Like @excentris said:
- Habits
- Dailies
- To-Dos
- Profile/Stats
  Watch out for v1.3. It is coming during weekend. _Crossed fingers_
