### ISSUE TITLE
Task names cut off very early

### ISSUE THREAD

**Issue by phillipthelen** [kdemerath/Habitica-Tasks#9]
The text is always cut off after 2 or 3 words. Maybe there is a way to have them wrap to two lines (more would probably take up too much space) and/or decrease the font size?

**Comment by kdemerath** [comment]
There is a subtitle with the task name now. AFAIK in Pebble.js is no possibility to change font size for standard menu items.

**Comment by kdemerath** [comment]
Guessed where menu cuts of and tried to optimize `subtitle`. Other solutions appreciated.
